#pragma once

#define BLE_BATTERY_SERVICE_UUID                        "180f"
#define BLE_BATTERY_CHARACTERISTIC_UUID_LEVEL           "2a19"
#define BLE_BATTERY_CHARACTERISTIC_UUID_LEVEL_STATUS    "2bed"
#define BLE_BATTERY_CHARACTERISTIC_UUID_TIME_STATUS     "2bee"
#define BLE_BATTERY_CHARACTERISTIC_UUID_CRITICAL_STATUS "2be9"